name: Build Wheels

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_dist:
    name: Build epanet-parse distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build-requirements.txt

      - name: Build distribution
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.*
